"""Seeded demo data for the Notary Platform (WO-48/REQ-NP-012).

Creates the Northstar Air demo organization with environments, agents, systems,
and sample incidents so the Notary Platform has data to display on first load.
"""

from __future__ import annotations

from notary_platform.models import (
    Agent,
    CapturePolicy,
    Environment,
    Organization,
    SystemConnection,
)

DEMO_ORG = Organization(
    id="org:harborline-demo",
    name="Northstar Air",
    environments=["env:demo", "env:staging", "env:production"],
)

DEMO_ENVIRONMENTS = {
    "env:demo": Environment(id="env:demo", name="Demo", org_id="org:harborline-demo", kind="demo"),
    "env:staging": Environment(id="env:staging", name="Staging", org_id="org:harborline-demo", kind="staging"),
    "env:production": Environment(
        id="env:production", name="Production", org_id="org:harborline-demo", kind="production"
    ),
}

DEMO_AGENTS = [
    Agent(
        id="agent:support-bot-v42",
        name="Bereavement Support Bot (v42)",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        risk_tier="high",
        sdk_status="connected",
        sdk_version="1.2.0",
        last_seen="2026-07-18T00:00:00Z",
        scenario_count=3,
        capture_policy_count=1,
    ),
    Agent(
        id="agent:support-bot-v43",
        name="Bereavement Support Bot (v43)",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        risk_tier="high",
        sdk_status="connected",
        sdk_version="1.3.0",
        last_seen="2026-07-17T12:00:00Z",
        scenario_count=1,
        capture_policy_count=1,
    ),
    Agent(
        id="agent:support-bot-staging",
        name="Support Bot (Staging)",
        org_id="org:harborline-demo",
        environment_id="env:staging",
        risk_tier="medium",
        sdk_status="connected",
        sdk_version="1.1.0",
        last_seen="2026-07-15T00:00:00Z",
        scenario_count=0,
        capture_policy_count=0,
    ),
    Agent(
        id="agent:support-bot-dev",
        name="Support Bot (Dev)",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        risk_tier="medium",
        sdk_status="not_installed",
        scenario_count=0,
        capture_policy_count=0,
    ),
]

DEMO_SYSTEMS = [
    SystemConnection(
        id="sys:notary-sdk",
        name="Notary Python SDK",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="sdk",
        type="capture_source",
        status="connected",
        auth_status="api_key",
        capability="Capture, Seal, Submit",
        supported_agents=["agent:support-bot-v42", "agent:support-bot-v43", "agent:support-bot-staging", "agent:support-bot-dev"],
        capture_policies=["policy:default-capture"],
        next_action="Use SDK install instructions to connect your agents",
    ),
    SystemConnection(
        id="sys:notary-api",
        name="Notary API",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="api",
        status="connected",
        auth_status="api_key",
        capability="Ingest, Replay, Certify",
        next_action="Create an API key in Settings",
    ),
    SystemConnection(
        id="sys:salesforce-service-cloud",
        name="Salesforce Service Cloud",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="source_system",
        status="connected",
        auth_status="api_key",
        capability="Case management and customer records",
        supported_agents=["agent:support-bot-v42", "agent:support-bot-v43"],
        next_action="Healthy — case #50093821 ingested",
    ),
    SystemConnection(
        id="sys:bereavement-policy-api",
        name="Bereavement Policy API",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="tool_api",
        status="connected",
        auth_status="api_key",
        capability="Cassette-backed policy lookup",
        sandbox_supported=True,
        sandbox_replay_modes=["cassette"],
        next_action="Healthy — replay uses cassette",
    ),
    SystemConnection(
        id="sys:nri-ticketing",
        name="NRI Support Ticketing",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="webhook",
        type="source_system",
        status="connected",
        auth_status="webhook_secret",
        capability="Ticket-based manual/webhook submissions",
        supported_agents=["agent:support-bot-v42", "agent:support-bot-v43"],
        next_action="Configure webhook URL and secret",
    ),
    SystemConnection(
        id="sys:passenger-booking",
        name="Passenger Booking System",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="source_system",
        status="connected",
        auth_status="api_key",
        capability="Booking and itinerary records",
        supported_agents=["agent:support-bot-v42", "agent:support-bot-v43"],
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:refund-api",
        name="Refund Processing API",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="tool_api",
        status="disconnected",
        auth_status="missing",
        capability="Refund/chargeback processing",
        supported_agents=["agent:support-bot-v42"],
        fallback="Use manual refund until API is connected",
        next_action="Connect refund API credentials",
    ),
    SystemConnection(
        id="sys:payment-gateway",
        name="Payment Gateway",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="tool_api",
        status="connected",
        auth_status="api_key",
        capability="Payment and refund transaction lookup",
        sandbox_supported=True,
        sandbox_replay_modes=["cassette"],
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:knowledge-base",
        name="Bereavement Policy KB",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="tool_api",
        status="connected",
        auth_status="api_key",
        capability="Retrieval-augmented policy context",
        sandbox_supported=True,
        sandbox_replay_modes=["cassette"],
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:azure-openai",
        name="Azure OpenAI (GPT-4o)",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="model_provider",
        status="connected",
        auth_status="api_key",
        capability="LLM inference",
        sandbox_supported=True,
        sandbox_replay_modes=["temp_zero", "seeded"],
        limitations=["LLM outputs are non-deterministic even with temp=0"],
        next_action="Use temp=0 / seeded calls for best replay",
    ),
    SystemConnection(
        id="sys:grc",
        name="GRC System",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="grc",
        type="grc_system",
        status="planned",
        auth_status="not_configured",
        capability="Evidence push and compliance reports",
        fallback="Export JSON/PDF manually until connector is built",
        next_action="Planned — configure after design partner onboarding",
    ),
    SystemConnection(
        id="sys:kms",
        name="AWS KMS",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="api",
        status="connected",
        auth_status="iam_role",
        capability="Certificate signing",
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:evidence-store",
        name="S3 Evidence Store",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="api",
        status="connected",
        auth_status="iam_role",
        capability="Immutable evidence storage",
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:github-actions",
        name="GitHub Actions",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        kind="api",
        type="cicd_system",
        status="planned",
        auth_status="not_configured",
        capability="Scenario runs block releases",
        fallback="Manual scenario review until release gate is built",
        next_action="Planned — configure after scenario library",
    ),
]

DEMO_POLICIES = [
    CapturePolicy(
        id="policy:default-capture",
        name="Default Capture Policy",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        status="active",
        coverage="all",
    ),
    CapturePolicy(
        id="policy:support-bot-capture",
        name="Support Bot Capture Policy",
        org_id="org:harborline-demo",
        environment_id="env:demo",
        agent_id="agent:support-bot-v42",
        status="active",
        coverage="all",
    ),
]


def seed() -> dict:
    return {
        "organization": DEMO_ORG,
        "environments": list(DEMO_ENVIRONMENTS.values()),
        "agents": DEMO_AGENTS,
        "systems": DEMO_SYSTEMS,
        "policies": DEMO_POLICIES,
    }
