"""Seeded demo data for the Notary Platform (WO-48/REQ-NP-012).

Creates a demo organization with environments, agents, systems, and sample
incidents so the Notary Platform has data to display on first load.
"""

from __future__ import annotations

from notary_platform.models import (
    Agent,
    CapturePolicy,
    Environment,
    Organization,
    SystemConnection,
)

DEMO_ORG = Organization(
    id="org:acme-demo",
    name="Acme Assurance Demo",
    environments=["env:demo", "env:staging", "env:production"],
)

DEMO_ENVIRONMENTS = {
    "env:demo": Environment(id="env:demo", name="Demo", org_id="org:acme-demo", kind="demo"),
    "env:staging": Environment(id="env:staging", name="Staging", org_id="org:acme-demo", kind="staging"),
    "env:production": Environment(
        id="env:production", name="Production", org_id="org:acme-demo", kind="production"
    ),
}

DEMO_AGENTS = [
    Agent(
        id="agent:lending",
        name="Lending Decision Agent",
        org_id="org:acme-demo",
        environment_id="env:demo",
        risk_tier="high",
        sdk_status="connected",
        sdk_version="1.2.0",
        last_seen="2026-07-18T00:00:00Z",
        scenario_count=3,
        capture_policy_count=1,
    ),
    Agent(
        id="agent:support-handoff",
        name="Support Handoff Agent",
        org_id="org:acme-demo",
        environment_id="env:demo",
        risk_tier="medium",
        sdk_status="connected",
        sdk_version="1.1.0",
        last_seen="2026-07-17T12:00:00Z",
        scenario_count=1,
        capture_policy_count=1,
    ),
    Agent(
        id="agent:prior-auth",
        name="Prior Authorization Agent",
        org_id="org:acme-demo",
        environment_id="env:demo",
        risk_tier="high",
        sdk_status="stale",
        sdk_version="0.9.0",
        last_seen="2026-07-01T00:00:00Z",
        scenario_count=0,
        capture_policy_count=0,
    ),
    Agent(
        id="agent:hiring-screen",
        name="Hiring Screen Agent",
        org_id="org:acme-demo",
        environment_id="env:demo",
        risk_tier="medium",
        sdk_status="not_installed",
        scenario_count=0,
        capture_policy_count=0,
    ),
]

DEMO_SYSTEMS = [
    SystemConnection(
        id="sys:notary-sdk",
        name="Notary Python SDK",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="sdk",
        type="capture_source",
        status="connected",
        auth_status="api_key",
        capability="Capture, Seal, Submit",
        supported_agents=["agent:lending", "agent:support-handoff", "agent:prior-auth", "agent:hiring-screen"],
        capture_policies=["policy:default-capture"],
        next_action="Use SDK install instructions to connect your agents",
    ),
    SystemConnection(
        id="sys:notary-api",
        name="Notary API",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="api",
        status="connected",
        auth_status="api_key",
        capability="Ingest, Replay, Certify",
        next_action="Create an API key in Settings",
    ),
    SystemConnection(
        id="sys:lending",
        name="Lending Decision System",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="source_system",
        status="connected",
        auth_status="api_key",
        capability="Loan underwriting decisions",
        supported_agents=["agent:lending"],
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:credit-bureau",
        name="Credit Bureau API",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="tool_api",
        status="connected",
        auth_status="api_key",
        capability="Cassette-backed response",
        sandbox_supported=True,
        sandbox_replay_modes=["cassette"],
        next_action="Healthy — replay uses cassette",
    ),
    SystemConnection(
        id="sys:support-ticketing",
        name="Support Ticketing",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="webhook",
        type="source_system",
        status="connected",
        auth_status="webhook_secret",
        capability="Ticket-based manual/webhook submissions",
        supported_agents=["agent:support-handoff"],
        next_action="Configure webhook URL and secret",
    ),
    SystemConnection(
        id="sys:prior-auth",
        name="Prior Authorization System",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="source_system",
        status="connected",
        auth_status="api_key",
        capability="Prior auth approvals/denials",
        supported_agents=["agent:prior-auth"],
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:hiring-ats",
        name="Hiring ATS",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="source_system",
        status="disconnected",
        auth_status="missing",
        capability="Resume screening submissions",
        supported_agents=["agent:hiring-screen"],
        fallback="Use manual submission until ATS connector is built",
        next_action="Connect ATS API credentials",
    ),
    SystemConnection(
        id="sys:payment-api",
        name="Payment / Refund API",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="tool_api",
        status="connected",
        auth_status="api_key",
        capability="Refund/chargeback lookup",
        sandbox_supported=True,
        sandbox_replay_modes=["cassette"],
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:claims-db",
        name="Claims Database",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="source_system",
        status="disconnected",
        auth_status="missing",
        capability="Historical claims state",
        fallback="Provide DB snapshot for full replay",
        limitations=["DB state not captured — replay is partial"],
        next_action="Configure read-only connector",
    ),
    SystemConnection(
        id="sys:knowledge-base",
        name="Knowledge Base",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="tool_api",
        status="connected",
        auth_status="api_key",
        capability="Retrieval-augmented context",
        sandbox_supported=True,
        sandbox_replay_modes=["cassette"],
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:model-provider",
        name="Model Provider",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="model_provider",
        status="connected",
        auth_status="api_key",
        capability="LLM inference",
        sandbox_supported=True,
        sandbox_replay_modes=["temp_zero", "seeded"],
        limitations=["LLM outputs are non-deterministic even with temp=0"],
        next_action="Use temp=0 / seeded calls for best replay",
    ),
    SystemConnection(
        id="sys:grc",
        name="GRC System",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="grc",
        type="grc_system",
        status="planned",
        auth_status="not_configured",
        capability="Evidence push and compliance reports",
        fallback="Export JSON/PDF manually until connector is built",
        next_action="Planned — configure after design partner onboarding",
    ),
    SystemConnection(
        id="sys:kms",
        name="AWS KMS",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="api",
        status="connected",
        auth_status="iam_role",
        capability="Certificate signing",
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:evidence-store",
        name="S3 Evidence Store",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="api",
        status="connected",
        auth_status="iam_role",
        capability="Immutable evidence storage",
        next_action="Healthy",
    ),
    SystemConnection(
        id="sys:cicd",
        name="CI/CD Release Gate",
        org_id="org:acme-demo",
        environment_id="env:demo",
        kind="api",
        type="cicd_system",
        status="planned",
        auth_status="not_configured",
        capability="Scenario runs block releases",
        fallback="Manual scenario review until release gate is built",
        next_action="Planned — configure after scenario library",
    ),
]

DEMO_POLICIES = [
    CapturePolicy(
        id="policy:default-capture",
        name="Default Capture Policy",
        org_id="org:acme-demo",
        environment_id="env:demo",
        status="active",
        coverage="all",
    ),
    CapturePolicy(
        id="policy:lending-capture",
        name="Lending Agent Policy",
        org_id="org:acme-demo",
        environment_id="env:demo",
        agent_id="agent:lending",
        status="active",
        coverage="all",
    ),
]


def seed() -> dict:
    return {
        "organization": DEMO_ORG,
        "environments": list(DEMO_ENVIRONMENTS.values()),
        "agents": DEMO_AGENTS,
        "systems": DEMO_SYSTEMS,
        "policies": DEMO_POLICIES,
    }
